name: Setup config

inputs:
  username:
    required: true
  botname:
    required: true
  password:
    required: true
  family:
    type: string
  mylang:
    type: string
  url:
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install deploy dependencies
      shell: bash
      run: |
        python3 -m pip install "mwparserfromhell>=0.5.0" pywikibot

    - name: Process
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        USERNAME: ${{ inputs.username }}
        BOTNAME: ${{ inputs.botname }}
        PASSWORD: ${{ inputs.password }}
        FAMILY: ${{ inputs.family }}
        MYLANG: ${{ inputs.mylang }}
        URL: ${{ inputs.url }}
      run: |
        python3 setup.py
