name: Deploy to MediaWiki

inputs:
  src:
    required: true
  dst:
    required: true
  summary:
    type: string

runs:
  using: "composite"
  steps:
    - name: Process
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        SRC: ${{ inputs.src }}
        DST: ${{ inputs.dst }}
        SUMMARY: ${{ inputs.summary }}
      run: |
        python3 deploy.py
