name: Deploy to MediaWiki

on:
  workflow_call:

jobs:
  create:
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3

      - uses: TNFSH-Programming-Contest/tps-actions/.github/actions/new-problem@main
        with:
          problem-count: ${{ inputs.count }}

      - name: Commit and Push
        run: |
          git add .problems.json
          git add Makefile
          git add README.md
          git add _config.yml
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git diff --cached --quiet || git commit -m "Create ${{ inputs.count }} problems"
          git push
